import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CodigosService {
  cp: any = [
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81200,
      "asentamiento" : "Primer Cuadro (Centro)",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81210,
      "asentamiento" : "Miguel Hidalgo",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81215,
      "asentamiento" : "ISSSTESIN",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81215,
      "asentamiento" : "Las Fuentes 2000",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81216,
      "asentamiento" : "Benito Juárez",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81216,
      "asentamiento" : "Bugambilias",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81216,
      "asentamiento" : "Gaviotas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81216,
      "asentamiento" : "Las Malvinas",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81216,
      "asentamiento" : "Reyes Guerrero",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81217,
      "asentamiento" : "Narciso Mendoza",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81218,
      "asentamiento" : "Prof. Conrado Espinoza",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81220,
      "asentamiento" : "Jiquilpan",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81220,
      "asentamiento" : "Jordan",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81220,
      "asentamiento" : "Sector Fátima",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81223,
      "asentamiento" : "Deportivo y Rincón",
      "tipo" : "Residencial"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81223,
      "asentamiento" : "Las Fuentes",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81224,
      "asentamiento" : "Juan Cota",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81225,
      "asentamiento" : "Ávila Corona",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81225,
      "asentamiento" : "Sanchez Ruiz",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81226,
      "asentamiento" : "Jardines de Fátima",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81227,
      "asentamiento" : "Fovissste",
      "tipo" : "Unidad habitacional"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81228,
      "asentamiento" : "Bosques Del Country",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81228,
      "asentamiento" : "Daniel Biul Ruelas",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81228,
      "asentamiento" : "Macapule Infonavit",
      "tipo" : "Unidad habitacional"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81228,
      "asentamiento" : "Privada Palladio",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81228,
      "asentamiento" : "Privada Toscana",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81228,
      "asentamiento" : "Residencial Campestre",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81228,
      "asentamiento" : "Viñedos Residencial",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81229,
      "asentamiento" : "Diamantes 2a Sección",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81229,
      "asentamiento" : "Fuentes Del Bosque",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81229,
      "asentamiento" : "Jiquilpan",
      "tipo" : "Ejido"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81229,
      "asentamiento" : "Palos Verdes Infonavit",
      "tipo" : "Unidad habitacional"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81229,
      "asentamiento" : "Residencial Diamante",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81229,
      "asentamiento" : "Tepeka",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81230,
      "asentamiento" : "Jardín",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81230,
      "asentamiento" : "Libertad",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81230,
      "asentamiento" : "Ruben Jaramillo",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81233,
      "asentamiento" : "Flor de las Arboledas",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81233,
      "asentamiento" : "FOVISSSTE 3",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81233,
      "asentamiento" : "Los Sabinos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81233,
      "asentamiento" : "Luis Donaldo Colosio",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Rural",
      "cp" : 81233,
      "asentamiento" : "México",
      "tipo" : "Ejido"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81233,
      "asentamiento" : "Nuevo Horizonte",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81233,
      "asentamiento" : "Providencia",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81233,
      "asentamiento" : "Residencial Palmira",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81233,
      "asentamiento" : "Valle Cañaveral",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81234,
      "asentamiento" : "75 (Heriberto Valdez Romero)",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81234,
      "asentamiento" : "Bosques del Pedregal",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81234,
      "asentamiento" : "Carolina Residencial",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81234,
      "asentamiento" : "Del Real",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81234,
      "asentamiento" : "El Chamizal",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81234,
      "asentamiento" : "Santa Fe",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81234,
      "asentamiento" : "Valle Bonito",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81235,
      "asentamiento" : "San Francisco",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81236,
      "asentamiento" : "10 de Mayo",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81236,
      "asentamiento" : "Alfonso G Calderón",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81237,
      "asentamiento" : "Estrella",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81238,
      "asentamiento" : "28 de Junio",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81238,
      "asentamiento" : "Adolfo Lopez Mateos",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Alfredo Salazar",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Alma Guadalupe Estrada",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Dolores Castro",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Ernesto Hays Borbo",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Germán Arroyo",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Ibarra",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Jordan Jiquilpan",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Julia Viuda de Ríos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Las Torres",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Mario Avilez",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Mayra H Pamplona",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Popular Blanca Gastelum",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Scally",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Toledo Ceballos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Valentín Gutiérrez",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81240,
      "asentamiento" : "Zaky Muez",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81245,
      "asentamiento" : "Deportivo Country Club",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81245,
      "asentamiento" : "Gastelum",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81245,
      "asentamiento" : "Grijalva",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81245,
      "asentamiento" : "Jardines Del Sol",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81245,
      "asentamiento" : "Jardines Del Valle",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81245,
      "asentamiento" : "Jordan Madero",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81245,
      "asentamiento" : "Ofelia Duarte",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81247,
      "asentamiento" : "Bachomo Infonavit",
      "tipo" : "Unidad habitacional"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81247,
      "asentamiento" : "Islas Residenciales",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81247,
      "asentamiento" : "Los Pinos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81247,
      "asentamiento" : "Los Sauces",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Álamo",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Álamos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Álamos I",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Álamos II",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Bosque del Real",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Cuauhtémoc",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Del Carmen",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Jardines del Bosque",
      "tipo" : "Residencial"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Jardines del Country",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Los Olivos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Monferrat",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Monico Soto",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Primavera",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Real del Country",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "Residencial del Country",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81248,
      "asentamiento" : "U.A.S. Álamos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81249,
      "asentamiento" : "INFONAVIT Mochicahui II",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81249,
      "asentamiento" : "Jardines de Zacatecas",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81249,
      "asentamiento" : "Las Palmas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81249,
      "asentamiento" : "Lastras Altamirano",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81249,
      "asentamiento" : "Menonitas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81249,
      "asentamiento" : "Progresivo San Rafael",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81249,
      "asentamiento" : "Residencial Del Valle",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81249,
      "asentamiento" : "Teresita",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81249,
      "asentamiento" : "Villas del Sol",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81250,
      "asentamiento" : "La Cuchilla",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81254,
      "asentamiento" : "Centro Plaza Mochis",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81254,
      "asentamiento" : "La Memoria",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81254,
      "asentamiento" : "Loma Dorada",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81254,
      "asentamiento" : "Los Mochis",
      "tipo" : "Parque industrial"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81254,
      "asentamiento" : "Mallorca",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81254,
      "asentamiento" : "Monte Carlo",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81254,
      "asentamiento" : "Versalles Residencial",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81255,
      "asentamiento" : "Zona Industrial",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81256,
      "asentamiento" : "Bellavista",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81256,
      "asentamiento" : "Central de Abastos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81256,
      "asentamiento" : "FOVISSSTE Tabachines IV",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81256,
      "asentamiento" : "INFONAVIT Mochicahui",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81256,
      "asentamiento" : "ing. Heriberto Valdez Romero",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81256,
      "asentamiento" : "Jiquilpan 2",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81256,
      "asentamiento" : "Lázaro Cárdenas",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81256,
      "asentamiento" : "Parque Industrial Ecológico",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81256,
      "asentamiento" : "Villa Huites",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81257,
      "asentamiento" : "Roberto Perez Jacobo",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81257,
      "asentamiento" : "Tabachines",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81257,
      "asentamiento" : "Villa Owen",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81259,
      "asentamiento" : "Del Parque",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81260,
      "asentamiento" : "Alejandro Peña",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81260,
      "asentamiento" : "Hacienda Santa Clara",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81260,
      "asentamiento" : "La Esperanza",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81260,
      "asentamiento" : "Las Mañanitas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81260,
      "asentamiento" : "Realito",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81260,
      "asentamiento" : "Rosendo G Castro",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81260,
      "asentamiento" : "Valle Verde",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81263,
      "asentamiento" : "Las Glorias",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81263,
      "asentamiento" : "Prados del Valle",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81263,
      "asentamiento" : "Residencial Aurora",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81263,
      "asentamiento" : "Santa Lourdes",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81263,
      "asentamiento" : "Santa Rosa",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81265,
      "asentamiento" : "Ferrocarril",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81265,
      "asentamiento" : "Residencial Ahome 2000",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Campanario",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Conquistadores",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Gabriel Leyva",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Jardines de Guadalupe",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Las Huertas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Las Huertas II",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Las Quintas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Los Naranjos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Margarita",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Paseo de las Aves",
      "tipo" : "Residencial"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Residencial Platino",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Salvador Esquer Apodaca",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "San Fernando",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Terranova",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Villa de Cortes",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81270,
      "asentamiento" : "Villas Monterrey",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "12 de Octubre",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Álamos Country",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Azucena",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Las Villas Residencial",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Paseo Alameda",
      "tipo" : "Residencial"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Portal de Hierro",
      "tipo" : "Residencial"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Quinta Real",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Real del Valle",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Residencial Paseo Alameda",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "San Fernando",
      "tipo" : "Ampliación"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Santa Bárbara",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Santa Cecilia",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Santa Teresa",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Sierra Bonita",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Tulipanes",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Villa de Cortez",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81271,
      "asentamiento" : "Zafiro",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81277,
      "asentamiento" : "Hacienda Arroyo Pioneros",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81277,
      "asentamiento" : "Hacienda del Arroyo",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81277,
      "asentamiento" : "Haciendas Country",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81277,
      "asentamiento" : "Las Delicias",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81277,
      "asentamiento" : "Las Haciendas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81277,
      "asentamiento" : "Palmera Residencial",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Alcázar del Country",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Cedros",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Colon",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "El Dorado",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Rural",
      "cp" : 81278,
      "asentamiento" : "Francisco Villa",
      "tipo" : "Ejido"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "La Esmeralda",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Los Virreyes",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Owen",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "San Isidro",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "San José",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Santa Alicia",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Santa Catalina",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Santa María",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Urbi Villa del Rey",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Valle de la Rosa",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81278,
      "asentamiento" : "Valle del Rey",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81280,
      "asentamiento" : "Anáhuac",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81280,
      "asentamiento" : "Bienestar",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81280,
      "asentamiento" : "Independencia",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81280,
      "asentamiento" : "Insurgentes Obrera",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81280,
      "asentamiento" : "Obrera",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81280,
      "asentamiento" : "Sinaloa",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81280,
      "asentamiento" : "Vivienda Popular",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "Antonio Toledo Corro",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "Francisco Labastida Ochoa",
      "tipo" : "Ampliación"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "La Florida",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "La Joya",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "Las Isabeles",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "Prados del Sur",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "Raul Romanillo",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "Residencial Mar de Cortés",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "STASE IV",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "STASE Los Álamos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "Tulipanes",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81285,
      "asentamiento" : "Universitario",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81289,
      "asentamiento" : "Americana",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81289,
      "asentamiento" : "La Herradura",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81289,
      "asentamiento" : "Parque Sinaloa",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81290,
      "asentamiento" : "Ampliación Burócrata",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81290,
      "asentamiento" : "Burócrata",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81290,
      "asentamiento" : "Lopez Portillo",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81290,
      "asentamiento" : "Morelos",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81293,
      "asentamiento" : "Jardines de Villa",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81293,
      "asentamiento" : "Las Misiones",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81293,
      "asentamiento" : "Las Nubes",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81293,
      "asentamiento" : "Mediterráneo",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81293,
      "asentamiento" : "Montebello",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81293,
      "asentamiento" : "Pradera de Villa",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81293,
      "asentamiento" : "Privanzas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81293,
      "asentamiento" : "Real de Villa",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81293,
      "asentamiento" : "Villa Centenario",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81293,
      "asentamiento" : "Villa de Santiago",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Almendras",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Ampliación Nuevo Siglo",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Camelias",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Catarinas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Jardines de Morelos",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Jardines de Primavera",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "La Cantera",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Las Cerezas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Semiurbano",
      "cp" : 81294,
      "asentamiento" : "Las Flores",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Lázaro Cárdenas Del Rio",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Los Laureles",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Niños Héroes",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Nueva Revolución",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Nuevo Siglo",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Prado Bonito",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Prados III",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Primavera CTELL 11",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81294,
      "asentamiento" : "Siglo XXI",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81295,
      "asentamiento" : "Las Cañas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81295,
      "asentamiento" : "Las Praderas",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81295,
      "asentamiento" : "Los Ángeles",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81295,
      "asentamiento" : "Los Girasoles",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81295,
      "asentamiento" : "Los Portales",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81295,
      "asentamiento" : "Morelos CTM",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81295,
      "asentamiento" : "Morelos CTM 2",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81295,
      "asentamiento" : "San Francisco",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 25,
      "estado" : "Sinaloa",
      "idMunicipio" : 1,
      "municipio" : "Ahome",
      "ciudad" : "Los Mochis",
      "zona" : "Urbano",
      "cp" : 81295,
      "asentamiento" : "Santa Luz",
      "tipo" : "Fraccionamiento"
    },
    {
      "idEstado" : 1,
      "estado" : "Aguascalientes",
      "idMunicipio" : 1,
      "municipio" : "Aguascalientes",
      "ciudad" : "Aguascalientes",
      "zona" : "Urbano",
      "cp" : 20000,
      "asentamiento" : "Zona Centro",
      "tipo" : "Colonia"
    },
    {
      "idEstado" : 1,
      "estado" : "Aguascalientes",
      "idMunicipio" : 1,
      "municipio" : "Aguascalientes",
      "ciudad" : "Aguascalientes",
      "zona" : "Urbano",
      "cp" : 20010,
      "asentamiento" : "Colinas del Rio",
      "tipo" : "Fraccionamiento"
    },
  ]
  
  getcp(){
    return this.cp;
  }
  
  constructor() { 

  }
}
